const localStaffList = [
  {
    id: 7,
    titleKR: "대표이사",
    titleENG: "CEO",
    nameKR: "이 영 숙",
    nameENG: "Young-sook Lee",
    infoKR1:
      "- 이화여자대학교 정치외교학과 졸업\r\n- 1986년 KBS < 르포 20/20 >으로 작가 데뷔. MBC, KBS, SBS 작가 활동\r\n- (前) 대전 배재대학교 교수\r\n- (前) 한국방송작가협회 이사",
    infoKR2:
      "- (前) 한국방송영상제작사협회 부회장\r\n- (現) 아이엠티브이 대표이사\r\n- MBC < 러시아 동구의 문학과 예 술 > / 한국방송대상 최우수 작품상 수상\r\n- MBC < 한민족 러시아 유민사 >(4부작) / 한국방송대상 최우수 작품상 수상\r\n",
    infoKR3:
      "- KBS < 10대 문화유산 시리즈 > ‘황룡사’ / 한국방송대상 실험정신상 수상\r\n- SBS 광복절 특집 < 조총련 사람들 >(2부작) / 한국방송위원회 대상 수상\r\n- SBS < 그것이 알고 싶다 > 집필 (50여편)\r\n- KBS < 역사스페셜 > 다수 집필\r\n",
    infoKR4:
      "- MBC < 이제는 말할 수 있다 > 기획/집필,~- 한국방송위원회 선정 ‘해외 한국어지원방송 예술부문’ 총괄\r\n- KBI NGCI 공동 선정 < Korea to the world > 프로그램 총괄\r\n- 내셔널지오그래픽 Europe, Asia 방영 < Health Secrets Behind Korean Cuisine > 총괄\r\n- 2007년 KBI국제심포지엄(4월), BCWW(8월), NOVA 퍼런스(10월) 공동제작,포럼 발표 및 토론 패널\r\n",
    infoKR5:
      "- 2008년도 프랑스 MIP TV Contents 360 본선 프레젠터\r\n- 영화 < 내 연애의 기억 > 제작, NAVER 웹드라마 < 0시의 그녀 > 제작\r\n-  KBS 어린이드라마 < 마법천자문 > 제작\r\n- SBS 수목 미니시리즈 < 다시 만난 세계 > 제작\r\n",
    infoKR6:
      "- KBS 금요 미니시리즈 < 스파이 > 제작\r\n- OCN 월화 로맨스 < 그남자 오수 > 제작\r\n- 웹무비 < Memento-mori > 제작  ☜ 2018 CANNESERIES Festival Digital contents competition finalist / 2018 서울 웹페스트 대상\r\n- 2021년 KT 오리지널 드라마 < 쉿! 그놈을 부탁해 > 제작,외 100여편의 작품 집필, 총괄 프로듀서 및 제작한 국내 정상급 크리에이터]\r\n",
    infoKR7: "",
    infoKR8: "",
    infoKR9: "",
    infoKR10: "",
    infoENG1:
      "- CEO of IMTV\r\n- Graduated from Ewha Womans University, Political Science and Diplomacy\r\n- In 1986, she made her debut as a writer with KBS <Repo 20/20>. MBC, KBS, SBS Writers Activities\r\n- (former professor at Baejae University in Daejeon)\r\n",
    infoENG2:
      " - (former director of the Korea Broadcasting Writers Association)\r\n- (Former vice chairman of the Korea Broadcasting and Video Producers Association)\r\n- MBC Literature and Art in Eastern Russia / Best Picture Award at Korea Broadcasting Awards\r\n- MBC Korean Russian Yoo Min-sa (4 episodes) / Best Picture Award at the Korea Broadcasting Awards\r\n",
    infoENG3:
      "- KBS Ten Cultural Heritage Series Hwangnyongsa / Korea Broadcasting Awards for Experimental Spirit Award\r\n- SBS Liberation Day Special Chochongryeon People (2 episodes) / Korea Broadcasting Commission Grand Prize Award\r\n - SBS I Want To Know (about 50 episodes), KBS History Special Written by IMTV MBC I can say it now  Planning/Writing\r\n- The Korea Broadcasting Commissions selection of Overseas Korean Support Broadcasting Art Division\r\n",
    infoENG4:
      "- KBI NGCI Co-Selected Korea to the world Program Executive Director,\r\n- Health Secrets behind Korean Cuisine by National Geographic Europe, Asia, \r\n- 2007 KBI International Symposium (April), BCWWW (August), NOVA Performance (October) co-producer, Forum Presentation and Discussion Panel\r\n- 2008 French MIP TV Contents 360 Final Presenter\r\n- Produced Memories of My Dating, NAVER web drama Missing You, KBS Children Drama Magic Scroll> SBS Wednesday/Thursday mini-series, Into the New World, KBS Friday mini-series Spy, OCN Monday-Tuesday Romance The Man Osu, KT`s original drama, Shh! Please Take Care of Him\r\n",
    infoENG5:
      "- Web Movie Memento Mori Production ☜ 2018 CANNESERIES Festival Digital Contents competition finalist / 2018 Seoul Web Fest Grand Prize",
    infoENG6: "",
    infoENG7: "",
    infoENG8: "",
    infoENG9: "",
    infoENG10: "",
  },
  {
    id: 8,
    titleKR: "총괄 부사장 / 프로듀서",
    titleENG: "Executive Vice President / Producer",
    nameKR: "이 상 현",
    nameENG: "Lee Sang-hyeon",
    infoKR1:
      "이화여자대학교 정치외교학과 졸업,\r\n1986년 KBS < 르포 20/20 >으로 작가 데뷔. MBC, KBS, SBS 작가 활동,\r\n(前) 대전 배재대학교 교수,\r\n(前) 한국방송작가협회 이사,\r\n(前) 한국방송영상제작사협회 부회장,\r\n(現) 아이엠티브이 대표이사,\r\nMBC < 러시아 동구의 문학과 예술 > / 한국방송대상 최우수 작품상 수상,\r\nMBC < 한민족 러시아 유민사 >(4부작) / 한국방송대상 최우수 작품상 수상,\r\nKBS < 10대 문화유산 시리즈 > ‘황룡사’ / 한국방송대상 실험정신상 수상,\r\nSBS 광복절 특집 < 조총련 사람들 >(2부작) / 한국방송위원회 대상 수상,\r\nSBS < 그것이 알고 싶다 > 집필 (50여편),\r\nKBS < 역사스페셜 > 다수 집필,\r\nMBC < 이제는 말할 수 있다 > 기획/집필,\r\n한국방송위원회 선정 ‘해외 한국어지원방송 예술부문’ 총괄,\r\nKBI\r\nNGCI 공동 선정 < Korea to the world > 프로그램 총괄,\r\n내셔널지오그래픽 Europe, Asia 방영 < Health Secrets Behind Korean Cuisine > 총괄,\r\n2007년 KBI국제심포지엄(4월), BCWW(8월), NOVA 퍼런스(10월) 공동제작,포럼 발표 및 토론 패널,\r\n2008년도 프랑스 MIP TV Contents 360 본선 프레젠터,\r\n영화 < 내 연애의 기억 > 제작,\r\nNAVER 웹드라마 < 0시의 그녀 > 제작,\r\nKBS 어린이드라마 < 마법천자문 > 제작,\r\nSBS 수목 미니시리즈 < 다시 만난 세계 > 제작,\r\nKBS 금요 미니시리즈 < 스파이 > 제작,\r\nOCN 월화 로맨스 < 그남자 오수 > 제작,\r\n웹무비 < Memento\r\nmori > 제작 ☜ 2018 CANNESERIES Festival Digital contents competition finalist / 2018 서울 웹페스트 대상,\r\n2021년 KT 오리지널 드라마 < 쉿! 그놈을 부탁해 > 제작,외 100여편의 작품 집필, 총괄 프로듀서 및 제작한 국내 정상급 크리에이터]",
    infoKR2: "",
    infoKR3: "",
    infoKR4: "",
    infoKR5: "",
    infoKR6: "",
    infoKR7: "",
    infoKR8: "",
    infoKR9: "",
    infoKR10: "",
    infoENG1:
      "[Major experience],\r\nGraduated from Yonsei University in Sociology,\r\nCable MYTV, KBS Sunday Special Team, SIS Satellite TV, J\r\nPro PD,\r\nDREAM SAVER, Director of Reality Vision Planning,\r\n(i) Executive Vice President/Producer of IMTV,[Main work],\r\nDirected by KBS [Daddy Whistle], [Document court tracking], [Document boys and girls],\r\nKBS [Hospital 24:00],\r\nSBS [Guardian Angel to Escape Crisis] Planning,\r\nNational Geographic Channel (NGC) documentary, about 10 production producers,\r\nJTBC Documentary [Bernard Werber`s Cat Dictionary],\r\nKBS Documentary[도도국CSD,\r\nTVing [Vegetarian Food] Project,\r\nFormat XtvN [Romantamjeong] Planning,\r\nJTBC [Open Man and Woman] Planning,\r\nSBS Drama [Into the New World] Production Manager,\r\nKBS Drama `Spy`, `Magic Thousand\r\nCharacter` Project Manager,\r\nOCN Drama [The Man Who Osu] Business Executive,\r\nKT web drama. [Shh!] the head of the business,\r\nNave Webdrama [0 o`clock girl], [Milkid] Planning and business executive,\r\nMovie [Memories of My Love], [Mementomori] Planning Producer",
    infoENG2: "",
    infoENG3: "",
    infoENG4: "",
    infoENG5: "",
    infoENG6: "",
    infoENG7: "",
    infoENG8: "",
    infoENG9: "",
    infoENG10: "",
  },
  {
    id: 9,
    titleKR: "경영본부장 / 이사",
    titleENG: "Head of Management / Director",
    nameKR: "안 휘 수",
    nameENG: "An Hui-Su ",
    infoKR1:
      "[주요 경력],\r\n연세대학교 경제학과,\r\n(前) Ernst & Young Parthenon CFS, 전략 컨설턴트,\r\n(前) 프레시지 경영관리실장, 상무,\r\n(現) 아이엠티브이 경영 본부장, 이사",
    infoKR2: "",
    infoKR3: "",
    infoKR4: "",
    infoKR5: "",
    infoKR6: "",
    infoKR7: "",
    infoKR8: "",
    infoKR9: "",
    infoKR10: "",
    infoENG1:
      "[Major experience],\r\nDepartment of Economics at Yonsei University,\r\n(Former) Ernst & Young Parthenon CFS, Strategic Consultant,\r\n(Former) Presidential Chief of Management, Managing Director, Pressey,\r\n(i) Director, Management Division of IMTV",
    infoENG2: "",
    infoENG3: "",
    infoENG4: "",
    infoENG5: "",
    infoENG6: "",
    infoENG7: "",
    infoENG8: "",
    infoENG9: "",
    infoENG10: "",
  },
  {
    id: 10,
    titleKR: "해외사업 팀장 / 프로듀서",
    titleENG: "Head of Global Content / Producer",
    nameKR: "장 조셉",
    nameENG: "Joseph Jang",
    infoKR1:
      "[주요 경력],\r\nCal Poly Pomona 영어학과 졸업,\r\nSeattle University School of Law 졸업,\r\nATTORNEY,\r\n스테디캠 촬영감독,\r\n드라마빈스 코리아 대표,\r\n팬텀 파운데이션 COO,\r\n아이엠티브이 해외 사업 팀장/프로듀서,[주요 작품],\r\n미국 독립영화 [The Lurk],\r\n미국 단편영화 [Jonathan],\r\n미국 단편영화 [Picture Perfect],\r\n브랜드 영상 [LG, 삼성],\r\n브랜드 영상 [Rode Electronics],\r\n뮤직비디오 [2NE1, EXO]",
    infoKR2: "",
    infoKR3: "",
    infoKR4: "",
    infoKR5: "",
    infoKR6: "",
    infoKR7: "",
    infoKR8: "",
    infoKR9: "",
    infoKR10: "",
    infoENG1:
      "[Major experience],\r\nGraduated from Cal Poly Pomona, English Department,\r\nGraduated from Seattle University School of Law,\r\nATTORNEY,\r\nSteady cam director,\r\nDrama Vince Korea`s representative,\r\nPhantom Foundation COO,\r\nIMTV`s Overseas Business Team Leader/Producer,[Main work],\r\nAmerican Independent Film [The Lurk],\r\nJonathan, American Short Film, Jonathan],\r\nAmerican Short Film [Picture Perfect],\r\nBrand Video [LG, Samsung],\r\nBrand Video [Rode Electronics],\r\nMusic video [2NE1, EXO]]",
    infoENG2: "",
    infoENG3: "",
    infoENG4: "",
    infoENG5: "",
    infoENG6: "",
    infoENG7: "",
    infoENG8: "",
    infoENG9: "",
    infoENG10: "",
  },
  {
    id: 11,
    titleKR: "다큐멘터리 - 프로그램 제작 본부장 / 프로듀서",
    titleENG: "Documentary Director/Producer",
    nameKR: "신 성 필",
    nameENG: "Shin Sang-Pil ",
    infoKR1:
      "[주요 경력],\r\n서강대학교 사학과 졸업,\r\n아이엠티브이 PD / 제작팀장,\r\n(現) 아이엠티브이 프로그램 제작본부장(교양.다큐.예능)/프로듀서,[주요 작품],\r\nKBS [생로병사의 비밀], [신화창조의 비밀], [과학카페], [현장르포 동행] 등 연출,\r\nNational Geographic Channel (NGC) 다큐멘터리 [해녀의 섬, 제주] [세상에서 가장 큰 백화점] 연출,\r\nKBS [동행], [황금연못], [사장님이 미쳤어요], EBS [비욘드], MBN [현장르포 특종세상], SBS [물은 생명이다] 제작 팀장,\r\n다큐멘터리 JTBC [베르나르 베르베르의 고양이 사전], Tving [요즘 채식], [브레드 오딧세이] 제작 총괄",
    infoKR2: "",
    infoKR3: "",
    infoKR4: "",
    infoKR5: "",
    infoKR6: "",
    infoKR7: "",
    infoKR8: "",
    infoKR9: "",
    infoKR10: "",
    infoENG1:
      "[Major experience],\r\nGraduated from Sogang University, History Department,\r\nI.M.T. PD / Production Team Leader,\r\n(i) Director of Production Division of IMTV Program (Cultivation and Documentation).entertainment)/producer,[Main work],\r\nKBS, `Secret of Life Soldiers`, `Secret of SHINHWA Creation`, `Science Cafe`, `Site Repo Companion`, etc,\r\nDirected by National Geographic Channel (NGC) documentary, Jeju Island, the biggest department store in the world,\r\nKBS [Companion], [Golden Pond], [The Boss Is Crazy], EBS [Beyond], MBN [Scene Lefo Screaming World], SBS [Water is Life] Production Team Leader,\r\nDocumentary JTBC [Bernard Werber`s Cat Dictionary], Tving [Vegetable These Days], [Bread Odyssey] Production Executive",
    infoENG2: "",
    infoENG3: "",
    infoENG4: "",
    infoENG5: "",
    infoENG6: "",
    infoENG7: "",
    infoENG8: "",
    infoENG9: "",
    infoENG10: "",
  },
  {
    id: 12,
    titleKR: "다큐멘터리 - 프로그램 제작 본부장 / 프로듀서",
    titleENG: "Documentary Team Leader / Producer",
    nameKR: "성 혜 정",
    nameENG: "Song Hye-Jong ",
    infoKR1:
      "[주요 경력],\r\n경희대학교 영어학과 졸업,\r\n(現) 아이엠티브이 다큐멘터리 제작팀장/프로듀서,[주요 작품],\r\nKBS [과학카페], [현장프로 동행], [생로병사의 비밀], [이웃집 찰스], [사장님이 미쳤어요], MBC [문화사색], EBS [비욘드] 연출,\r\nNational Geographic Channel 다큐멘터리 [Get Lost in Korea] 연출,\r\n다큐멘터리 KBS [월드뮤직\r\n쿠바편], KBS 다큐공감 [손끝의 기적\r\n감사합니다], SKY UHD [실흠의 탄생], KBS [도시가 살아난다], [동양정신에 길을 묻다], CJ UXN [breaking Limits], JTBC [베르나르 베르베르의 고양이 사전], KBS [차도삼국지], Tving [요즘 채식] 연출",
    infoKR2: "",
    infoKR3: "",
    infoKR4: "",
    infoKR5: "",
    infoKR6: "",
    infoKR7: "",
    infoKR8: "",
    infoKR9: "",
    infoKR10: "",
    infoENG1:
      "[Major experience],\r\nGraduated from Kyung Hee University, majoring in English,\r\n(i) Director/producer of iMTV documentary production team,[Main work],\r\nKBS [Science Cafe], [On\r\nSite Professional Accompanying], [Secret of Life Soldiers], [Neighbor Charles], [The Boss Is Crazy], MBC [Culture Thinking], EBS [Beyond] Directed,\r\nNational Geographic Channel documentary, directed by [Get Lost in Korea],\r\nDocumentary KBS [World Music\r\nCuba], KBS Documentary Sympathy [Miracle of the Finger\r\nThank You], SKY UHD [Birth of Silheum], KBS [City Resurrects], CJ UXN [Breaking Limits], JTBC [Bernard Verber`s Cat Dictionary], KBS [Chado Samgukji], Tving] [Vegetarian]",
    infoENG2: "",
    infoENG3: "",
    infoENG4: "",
    infoENG5: "",
    infoENG6: "",
    infoENG7: "",
    infoENG8: "",
    infoENG9: "",
    infoENG10: "",
  },
  {
    id: 13,
    titleKR: " 팩추얼 기획 팀장 / 작가",
    titleENG: "Factual Planning Team Leader / Writer",
    nameKR: "박 남 숙",
    nameENG: "Park Nam-sook ",
    infoKR1:
      "[주요 경력],\r\n전남대학교 독일언어문학과 졸업,\r\nSBS 아카데미 구성작가반 수료,\r\n(現) 아이엠티브이 팩추얼 기획팀장/작가,[주요 작품],\r\nKBS [신화창조의 비밀], [과학카페], [현장프로 동행], [생로병사의 비밀], [추적 60분], [이웃집 찰스], 채널A [그여자 그남자], EBS [달라졌어요] 작가,\r\nNational Geographic Channel (NGC) 다큐멘터리 [Korean Soul Food, [Inside K\r\nFood] 작가,\r\nKBS역사스페셜 [외규장각편, 최윤덕편], KBS스페셜 [질주본능], EBS [비욘드] 작가,\r\n다큐멘터리 KBS [월드뮤직\r\n쿠바편], MBC [우리 엄마 순애씨], SKY UHD [실흠의 탄생], JTBC [베르나르 베르베르의 고양이 사전], KBS [차도삼국지], TVing [요즘 채식] 작가,",
    infoKR2: "",
    infoKR3: "",
    infoKR4: "",
    infoKR5: "",
    infoKR6: "",
    infoKR7: "",
    infoKR8: "",
    infoKR9: "",
    infoKR10: "",
    infoENG1:
      "[Major experience],\r\nGraduated from Chonnam National University in German Language and Literature,\r\nSBS Academy Composition Writer Class Completed,\r\n(i) IMTV Factual Planning Team Leader/Writer,[Main work],\r\nKBS [Secret of Shinhwa Creation], [Science Cafe], [On\r\nSite Professional Accompanying], [Secret of Life Soldiers], [60 Minutes of Tracking], [My Neighbor Charles], Channel A [She] and EBS [Changed] Writers,\r\nAuthor of the National Geographic Channel (NGC) documentary, Korean Soul Food, Inside K\r\nFood,\r\nKBS History Special [Oekyu Janggak, Choi Yoon\r\ndeok], KBS Special [Running Instinct], EBS [Beyond] Writers,\r\nWriters of documentaries KBS [World Music\r\nCuba], MBC [My Mom Soon\r\nae], SKY UHD [Birth of Silheum], JTBC [Bernard Werber`s Cat Dictionary], KBS [Chado Samgukji], TVing [Vegetarian]",
    infoENG2: "",
    infoENG3: "",
    infoENG4: "",
    infoENG5: "",
    infoENG6: "",
    infoENG7: "",
    infoENG8: "",
    infoENG9: "",
    infoENG10: "",
  },
  {
    id: 14,
    titleKR: "드라마부문 부사장 / 감독",
    titleENG: "Vice President/Director of Drama",
    nameKR: "전 산",
    nameENG: "Jon San ",
    infoKR1:
      "[주요 경력],\r\n성균관대학교 중문과 졸업,\r\n중앙대학교 영화학과 석사, 박사과정 수료,\r\n1985 KBS 입사 드라마국 PD,\r\n1992 KBS 드라마 <내일은 사랑>으로 데뷔,\r\n2004~06 KBS 편성본부 부실장,\r\n2007~10 KBS 드라마운영팀 CP,\r\n2014 KBS N 콘텐츠본부 본부장,\r\n2016 팬 엔터테인먼트 드라마사업부 총괄 부사장,\r\n2021 (현재) 아이엠티브이 드라마부문 부사장,[주요작품],\r\n1992 KBS 드라마게임 《쇼팽을 좋아하세요》,\r\n1992 KBS 드라마게임 《당신은 누구시길래》,\r\n1992~94 KBS 《내일은 사랑》,\r\n1995 KBS 《젊은이의 양지》,\r\n1996 KBS 《신TV문학관\r\n슈퍼마켓에서 길을 잃다》,\r\n1997 KBS 《파랑새는 있다》,\r\n1998 KBS 《맨발의 청춘》,\r\n1998~99 KBS 《천사의 키스》,\r\n2000 KBS 《나는 그녀가 좋다》,\r\n2012 KBS 《드라마 스페셜\r\n저어새, 날아가다》,\r\n2013~14 KBS 《루비 반지》,\r\n2015 KBS 《복면검사》",
    infoKR2: "",
    infoKR3: "",
    infoKR4: "",
    infoKR5: "",
    infoKR6: "",
    infoKR7: "",
    infoKR8: "",
    infoKR9: "",
    infoKR10: "",
    infoENG1:
      "[Major experience],\r\nGraduated from Sungkyunkwan University in Chinese Studies,\r\nMaster of Film and Ph.D. at Chung\r\nAng University,\r\n1985 KBS Drama Department Producer,\r\n1992 KBS drama `Tomorrow Is Love` debuts,\r\n2004\r\n06 Deputy Director of KBS Organization Headquarters,\r\n2007\r\n10 KBS Drama Operation Team CP,\r\n2014 Director of KBS N Content Headquarters,\r\n2016 Vice President, Drama Division, Fan Entertainment,\r\n2021 (present) Vice President of drama division of I.M.T,[Main Work],\r\n1992 KBS Drama Game `Do You Like Chopin?`》,\r\n1992 KBS Drama Game `Who Are You?`,\r\n1992~94 KBS `Tomorrow is Love`,\r\n1995 KBS `Young Man`s Sunshine`,\r\n1996 KBS `New TV Literature Museum\r\nLost in Supermarkets`,\r\n1997 KBS `The Bluebird`》,\r\n1998 KBS `Barefoot Youth`,\r\n1998\r\n99 KBS `Angel`s Kiss`,\r\n2000 KBS `I Like Her`,\r\n2012 KBS `Drama Special\r\nSpoonbirds, Flying`,\r\n2013\r\n14 KBS `Ruby Ring`,\r\n2015 KBS `The Masked Examination`",
    infoENG2: "",
    infoENG3: "",
    infoENG4: "",
    infoENG5: "",
    infoENG6: "",
    infoENG7: "",
    infoENG8: "",
    infoENG9: "",
    infoENG10: "",
  },
  {
    id: 15,
    titleKR: "드라마 제작 본부장 / 프로듀서",
    titleENG: "Director/Producer of Drama",
    nameKR: "임 영 진",
    nameENG: "Im Yeong-Jin ",
    infoKR1:
      "[주요 경력],\r\n동국대학교 연극영화과 졸업,\r\nCJ E&M 프로듀서,\r\n(現) 아이엠티브이 드라마 제작본부장/프로듀서,[주요 작품],\r\nKBS [스파이],\r\nSBS [다시 만난세계],‌\r\nNAVER 웹드라마 [밀키드],‌\r\nKT ORIGINAL [쉿! 그놈을 부탁해],‌\r\nNETFLIX [종말의 바보]",
    infoKR2: "",
    infoKR3: "",
    infoKR4: "",
    infoKR5: "",
    infoKR6: "",
    infoKR7: "",
    infoKR8: "",
    infoKR9: "",
    infoKR10: "",
    infoENG1:
      "[Major experience],\r\nGraduated from Dongguk University, Department of Theater and Film,\r\nProducer of CJ E&M,\r\n(i) Director/producer of IMTV drama production,[Main Work],\r\nKBS [Spy],\r\nSBS [Into the New World],\r\nNAVER web drama [Mealkid],\r\nKT ORIGINAL. [Shh!] [Please take care of him],\r\nNETFLIX [The fool of the end]",
    infoENG2: "",
    infoENG3: "",
    infoENG4: "",
    infoENG5: "",
    infoENG6: "",
    infoENG7: "",
    infoENG8: "",
    infoENG9: "",
    infoENG10: "",
  },
  {
    id: 16,
    titleKR: "드라마 기획 팀장 / 작가",
    titleENG: "Director of Drama/Writer",
    nameKR: "조 아 라 ",
    nameENG: "Jo Arah ",
    infoKR1:
      "[주요 경력],\r\n이화여자대학교 국어국문학과 졸업,\r\n(現) 아이엠티브이 드라마 기획팀장/작가,[주요 작품],\r\n넷플릭스 [종말의 바보],\r\n네이버 [밀키드],\r\nKT [쉿! 그놈을 부탁해] 등 기획",
    infoKR2: "",
    infoKR3: "",
    infoKR4: "",
    infoKR5: "",
    infoKR6: "",
    infoKR7: "",
    infoKR8: "",
    infoKR9: "",
    infoKR10: "",
    infoENG1:
      "[Major experience],\r\nGraduated from Ewha Womans University in Korean Language and Literature,\r\n(i) Director/writer of IMTV drama planning team,[Main Work],\r\nNetflix. [The fool of the end],\r\nNAVER! [Mealkid],\r\nKT! [Shh!]n= `Please Take Care of Him`",
    infoENG2: "",
    infoENG3: "",
    infoENG4: "",
    infoENG5: "",
    infoENG6: "",
    infoENG7: "",
    infoENG8: "",
    infoENG9: "",
    infoENG10: "",
  },
];

export default localStaffList;
