const mediaList = [
  {
    id: 1,
    titleKR: "쉿! 그놈을 부탁해",
    titleENG: "Shh! Take Care of Him.",
    mediaImg: "./assets/images/media/shhWide.png",
    mediaImgTall: "./assets/images/media/shhTall.jpg",
    clipVid: "https://youtu.be/0mC8ANbrC_s",
    fullVid: "https://youtu.be/5_youLWtOV8",
    channels: "olleh tv, Seezn, Skylife",
    date: "2021.05.28",
    directorKR: "이정훈",
    writerKR: "자인, 방사랑 ",
    starringKR: "김슬기, 이주우, 송지은, 강율",
    descriptionKR:
      "홍대 한복판에 수상한 네일샵이 오픈했다! 복수를 ‘시술’이라 부르는 네일샵 여자들의 화끈한 복수컨설팅!",
    directorENG: "Lee Jung Hoon",
    writerENG: "Jain, Bang Sarang ",
    starringENG: "Kim Seulgi, Lee Juwoo, Song Jieun, Kang Yul",
    descriptionENG:
      "A suspicious nail shop opened in the middle of Hongdae! The hot revenge consulting of nail shop women who call revenge 'procedure!'",
  },

  {
    id: 2,
    titleKR: "그남자 오수",
    titleENG: "Mr Osu",
    mediaImg: "./assets/images/media/osuWide.png",
    mediaImgTall: "./assets/images/media/osuTall.jpg",
    clipVid: "https://youtu.be/_JcnedmLy38",
    fullVid: "https://youtu.be/dAlrU9UYPXU",
    channels: "OCN",
    date: "2018.03.05 ~ 2018.04.24",
    directorKR: "남기훈",
    writerKR: "정유선",
    starringKR: "이종현, 김소은",
    descriptionKR:
      "연애감 없는 현대판 큐피드 남자 오수와 연애 허당녀 유리의 둘만 모르는 확실한 썸로맨스.",
    directorENG: "Nam Ki-hoon",
    writerENG: "Jeong Yoo-sun ",
    starringENG: "Jonghyun Lee, Soeun Kim",
    descriptionENG:
      "Mr Osu, a modern Cupid man without a sense of love begins a relationship with a woman named Yuri.",
  },

  {
    id: 3,
    titleKR: "메멘토모리",
    titleENG: "Memento Mori",
    mediaImg: "./assets/images/media/mementoWide.png",
    mediaImgTall: "./assets/images/media/mementoTall.jpg",
    clipVid: "https://youtu.be/oxOPg3AeteE",
    fullVid: "https://youtu.be/BMbQYtWmcmo",
    date: "2018.06.28",
    directorKR: "이철민",
    writerKR: "조규원, 오기원",
    starringKR: "황승언, 재희, 김호정, 차순배",
    descriptionKR:
      "갑자기 그들이 깨어났다.‌누구의 소행인지 알 수 없는 가운데 6명이 한 장소에서 동시에 깨어났다.‌연결고리가 없는 이들 6명이 벌이는 '생존 게임'이 시작됐다.",
    directorENG: "Lee Chul-min",
    writerENG: "Gyu-won Jo, Oh Ki-won ",
    starringENG: "Hwang Seung-eon, Jae-hee, Kim Ho-jeong, Cha Soon-bae",
    descriptionENG:
      "Six people woke up at the same time in one place, without knowing why. A 'survival game' played by these six people without a connection has begun..",
  },
  {
    id: 4,
    titleKR: "다시 만난 세계",
    titleENG: "Reunited World",
    mediaImg: "./assets/images/media/worldWide.png",
    mediaImgTall: "./assets/images/media/worldTall.jpg",
    clipVid: "https://youtu.be/kOeYJBzbLsI",
    fullVid: "https://youtu.be/SLaU1iEbwB0",
    channels: "SBS",
    date: "2017.07.07 ~ 2017.09.21",
    directorKR: "백수찬",
    writerKR: "이희명",
    starringKR: "여진구, 이연희",
    descriptionKR:
      "열아홉 살 청년과 같은 해 태어난 동갑 친구인 서른한 살 여자. 12년 나이 차이가 나는 동갑 소꿉친구 남녀의 판타지 로맨스.",
    directorENG: "Baek Soo-chan",
    writerENG: "Lee Hee-myung",
    starringENG: "Yeo Jin-goo, Lee Yeon-hee",
    descriptionENG:
      "A 31-year-old woman, a friend of the same age, was born the same year as a 19-year-old young man. Fantasy romance between childhood friends of the same age with a 12-year age difference.",
  },
  {
    id: 5,
    titleKR: "스파이",
    titleENG: "Spy",
    mediaImg: "./assets/images/media/spyWide.png",
    mediaImgTall: "./assets/images/media/spyTall.jpg",
    clipVid: null,
    fullVid: "https://youtu.be/ocWTnNFRyuA",
    channels: "SBS",
    date: "2015.01.09 ~ 2015.03.06",
    directorKR: "박현석",
    writerKR: "한상운, 이강",
    starringKR: "김재중, 배종옥, 유오성",
    descriptionKR:
      "전직 스파이. 지금은 평범한 가정주부인 혜림. 정보국에서 일하는 아들을 포섭하라는 청천벽력 같은 임무로 사랑하는 가족을 지키기 위해 다시 한번 스파이로 나선다.",
    directorENG: "Park Hyun-seok",
    writerENG: "Han Sang-woon, Lee Kang",
    starringENG: "Jaejoong Kim, Jongok Bae, Ohseong Yoo",
    descriptionENG:
      "Former Spy Hyerim is now an ordinary housewife. She becomes a spy once again to protect her beloved family on a mission to recruit her son who works for the intelligence service.",
  },
  {
    id: 6,
    titleKR: "내 연애의 기억",
    titleENG: "Memories of My Love",
    mediaImg: "./assets/images/media/memoriesWide.png",
    mediaImgTall: "./assets/images/media/memoriesTall.jpg",
    clipVid: null,
    fullVid: "https://youtu.be/cXH-AVPl8Bw",
    date: "2014.08.20",
    directorKR: "이권",
    writerKR: "정성숙, 이권 ",
    starringKR: "강예원, 송새벽",
    descriptionKR:
      "씁쓸한 기억만 남긴 여섯 번의 연애 후 다시는 연애 따위 하지 않으리라 마음먹은 은진(강예원). 하지만 그녀 앞에 나타난 순수하고 로맨틱한 현석(송새벽)으로 인해 은진은 다시 사랑을 시작하게 된다. 수상하게 달콤하고 심장 떨리게 로맨틱한 연애가 시작된다!",
    directorENG: "IMTV",
    writerENG: "Seong-Suk Jeong, Kwon Lee",
    starringENG: "Kang Ye-won, Song Sae-byeok",
    descriptionENG:
      "Eun-Jin (Kang Ye-Won) decides that she will never love again after six romances that leave only bitter memories. But when innocent and romantic Hyun-seok (Song Sebyok) who appears in front of her, Eun-jin begins to fall in love again. A sweet and heartbreaking romantic relationship begins!",
  },

  {
    id: 7,
    titleKR: "마법천자문 ",
    titleENG: "Magic Scroll",
    mediaImg: "./assets/images/media/magicWide.jpg",
    mediaImgTall: "./assets/images/media/magicTall.jpg",
    clipVid: null,
    fullVid: "https://youtu.be/HlVqt7ry-nQ",
    channels: "KBS2",
    date: "2014.08.06 ~ 2014.11.19",
    directorKR: "이청민",
    writerKR: "권인찬",
    starringKR: "신기준, 이지우, 천이슬",
    descriptionKR:
      "현실 세계에서 환생한 주인공들이 인간 세계에 던져진 10개의 한자 마법을 찾기 위해 벌이는 고군분투 이야기",
    directorENG: "Cheongmin Lee",
    writerENG: "Kwon In-chan",
    starringENG: "Ki-joon Shin, Ji-woo Lee, Lee Seul Cheon",
    descriptionENG:
      "Reincarnated heroes struggle to find 10 magic Chinese character scrolls thrown into the human world.",
  },
  {
    id: 8,
    titleKR: "곡비",
    titleENG: "Gokbi",
    mediaImg: "./assets/images/media/singWide.png",
    mediaImgTall: "./assets/images/media/singTall.png",
    clipVid: null,
    fullVid: "https://youtu.be/KVLRUu7m1a8",
    channels: "KBS",
    date: "2014.03.09",
    directorKR: "이은진",
    writerKR: "허지영",
    starringKR: "김유정, 서준영",
    descriptionKR:
      "‌조선시대를 배경으로 당시 양반가에서 상을 당했을 때 곡을 해야하는 노비들의 이야기를 그린 드라마",
    directorENG: "Eunjin Lee",
    writerENG: "Heo Ji-young",
    starringENG: "Kim Yoo-jung, Seo Jun-young",
    descriptionENG:
      "Set in the Joseon Dynasty, this drama depicts the story of slaves who had to sing when they were rewarded by a noble family at the time.",
  },
  {
    id: 9,
    titleKR: "0시의 그녀",
    titleENG: "Girl of 0am",
    mediaImg: "./assets/images/media/zeroWide.png",
    mediaImgTall: "./assets/images/media/zeroTall.png",
    clipVid: null,
    fullVid: "https://youtu.be/qDwp1jd2EMo",
    channels: "네이버 MBC every1",
    date: "2015.05.04",
    directorKR: "이철민",
    writerKR: "윤진",
    starringKR: "남태현, 김민지, 손진영",
    descriptionKR:
      "‌슈퍼스타를 꿈꾸던 주인공 지단.우연히 운영을 맡게된 노래방에서 수상한 알바생 세라를 통해 신비한 경험을 하게 되는데…",
    directorENG: "Lee Chul-min",
    writerENG: "Jin Yoon",
    starringENG: "Nam Tae-hyun, Kim Min-ji, Son Jin-young",
    descriptionENG:
      "Zidane dreamed of becoming a superstar. Accidentally taking over a karaoke bar, he is reminded of his dream when he meets part-timer Sera.",
  },
  {
    id: 10,
    titleKR: "밀키드 ",
    titleENG: "Meal Kid",
    mediaImg: "./assets/images/media/mealkidWide.jpg",
    mediaImgTall: "./assets/images/media/mealkidTall.jpg",
    clipVid: null,
    fullVid: "https://www.youtube.com/watch?v=xnecaOsKp0c",
    channels: "네이버",
    date: "2020.11.16",
    directorKR: "이창한",
    writerKR: "문소산",
    starringKR: "박나은, 정대현, 주호",
    descriptionKR:
      "‌최고의 맛을 추구하는 식품 회사 MD들의 좌충우돌 오피스 성장기",
    directorENG: "Changhan Lee",
    writerENG: "Mun So-san",
    starringENG: "Park Na-eun, Jeong Dae-hyun, Joo-ho",
    descriptionENG: "Food company MDs who pursue the best taste.",
  },
];

export default mediaList;
